### PR TITLE
Murray. Deeper Christian Life / Fruit of the Vine

### PR DESCRIPTION
**Pull request by truthsword**
Chapters 4 & 5 proofed

### CODE REVIEW

**Comment by truthsword** [comment]
Interestingly... the word "self-sacrifice" is absent from the OCR copy, multiple times, in the 2 books I'm working on.

**Comment by truthsword** [comment]
Rather than submit chapters, I will submit by book to minimize pull requests. I don't plan to add further commits to this pull. But who knows...

**Comment by truthsword** [comment]
In some cases the text is italicized, but in other cases, portions are in SMALL CAPS (I can't show that precisely here). For example...

"He anticipates and meets their wishes, and gives them HIS OWN LIFE the best exposition of His command."

The capitalized words are in "small cap" format in the original. In the OCR text file, this same sentence appears as:

"He anticipates and meets their wishes, and gives them His Own Life as the best exposition of His command."

Here the emphasis is largely lost to the reader. I'm wondering if this is intentional, or would we be better served by formatting these sections in **bold** (assuming we the use of small caps is undesired, or incapable by Markdown). This would then read...

"He anticipates and meets their wishes, and gives them **His own life** as the best exposition of His command."
 [Note: I went to lowercase except in reference to God (His).]

How should this be handled?

**Comment by lukewil** [comment]
I agree that Title Case is most definitely not the answer, and whether it's intentional or not, you're absolutely correct that it looses all effectiveness - I would just read that and go, "Why is that capitalized?"

It's a judgement call as far as I'm concerned. I personally have a love affair with small caps, but there is no elegant solutions for them all around, in particular in ePub/Kindle formats.

So my thought would be _bold it_ for now like you have - we can always do a search/replace to switch it to small caps in another format.

**Comment by truthsword** [comment]
I'm good with that. I looked around some of the markdown forums, and it
seemed that html was the only answer for small caps for now.

I'm not sure if you have any particular order you'd prefer I go through.
Unless you direct me otherwise, I'm going to work through the Andrew Murray
folder. I've already submitted two of his shorter works to you, which
helped me get a feel for this work process.

Right now I'm about 75% through Abide In Christ, and I plan to work through
his other works alphabetically, unless there's some other place you'd
rather me be.

**Pull request merged**
