### PR TITLE
\Murray\Be Perfect: Full text-proofed + formatted

### PR DESCRIPTION
**Pull request by truthsword**
full text
proofed, formatted

"98% ready"

### CODE REVIEW

**Comment by lukewil** [comment]
Thanks Bob!

I know it is a bit of a pain, but just for the sake of both clarity and reversibility, let's do different pull requests for different books. That way if there were some issue and we ever needed to revert back, it would only be on the one book, not both.  I'll add that bit of info into the documentation today, along with some other new tutorials I'm writing.

**Comment by truthsword** [comment]
Unless I'm doing something wrong, that seems to be a GitHub thing. Right
now GitHub automatically adds anything I sync to my local fork to open pull
requests. In this case, I never made a pull request for the second book...
it just got added on top of the earlier one that was open.

I noticed this on one of my first pull requests... that all subsequent
syncs ended up on the pending/open pull request.

When I submit a pull request for Book 1, that request remains open until
you can get to it, all further commit/syncs I do _automatically_ are added
to that same open pull request, without me initiating a second request. So
if I were to commit changes to Book 2 and sync that with my fork, somehow
that sync is automatically added to the open pull request I have waiting
for you.

There seems to be no way to have multiple pull requests.

I don't see an option to change this on my end. Maybe there's a way to
change this on your end, or maybe its related to the way the book library
is configured... or maybe this is just how GitHub works.

_The only thing I can do now... Is to avoid syncing my local (desktop)
changes with my fork, until you complete close/merge my previous open pull
request._

If I've overlooked something here, let me know... because in this case I
never knowingly made a pull request for the second book you markup you
received. It just happened.

**Comment by lukewil** [comment]
Interesting -  it's quite possible that it's the case and I didn't realize it, so my apologies! The growing pains of figuring out how this all works! I'm going to test it out on a dummy repo today to see it from the other side. 

Thanks for letting me know!

**Comment by truthsword** [comment]
No worries... If it's me, let me know how. I really hoped to keep book
submissions separate myself.

Bob

**Pull request merged**
