### PR TITLE
winslow/born_again footnotes

### PR DESCRIPTION
**Pull request by physicswizkid**

### CODE REVIEW

**Comment by lukewil** [comment]
Great job - footnotes are without a doubt the part of this process I find most laborious, so I _especially_ appreciate this pull!

**Comment by physicswizkid** [comment]
You're welcome. If I'm formatting everything how you want it (and you should double-check this), I don't mind it at all. This is my first time using github, is there a forum-type area where I can post questions/comments on both the editing process in general (your directions were a good start, but there are a number of details I'd like to know about) or the current status of a book in particular (like what I think I've already done on a book and things that I noticed but didn't fix yet)?

**Comment by lukewil** [comment]
What exactly are the details you'd like to know more about? I'm going to be writing more documentation of everything today, so I'd love to know. I know for sure that I will be dealing with some searches that should always be done at the end of every book (for instance, searching for a period without a space to the right, or an uppercase letter with lowercase on either side, etc.), and also spell checking.

If there's a specific issue you're having that I haven't addressed yet, the best thing to do would be to **start an new issue**. You can read more about them [here](https://guides.github.com/features/issues/). This way everyone who's following the project can get notifications, we can tag people (like @physicswizkid ), categorize them, etc. 

I think I'm going to open an issue myself for discussion about what to do related to book status issue that you're referencing. We're going to have to find a workable solution so that it's clear on which books all the main steps have been done.

**Comment by physicswizkid** [comment]
For the general questions:

In your instructions on markdown, you tell us how to italicize passages. The book I looked at has tons of italicization throughout. Do you want all of it marked? Also, something to watch for is the italicization leads to a number of errors, such as recognizing an italicized I (capital i) as a / (forward slash).

In the OCR process, I noticed that Google turned the original Bible references into the modern format (i.e. Rev. iii. 1. in the original shows up as Revelation 3:1). Do you want to have the references match the original text or show up in the modern format? (In the book I worked on, I switched the references in the subtitles of each chapter to the original, because I think it looks cooler that way, but I can change them back).

As for the book status, would it work to have another file in each book folder that is just a text document that we can update with what we've done or not done on a book?

**Comment by lukewil** [comment]
Good point about italics leading to OCR issues. There are so many little things like that that I _know_, but haven't found a good place to write them down yet. But I'm working on adding it. That capital `I` to forward slash is an ongoing issue, not just in italics.

One of the new bits of documentation that I'm working on is a standard set of searches that should be done on each book. This would be for things like slashes - there aren't any legit reasons for slashes to be in these books - it's an error 99.9% of the time. So by searching for it in every book we can make sure that all those `I`'s are actually `I`. I've got a whole list of things like this that I'll be making a nice list of.

I know some of the books can get a little wild with the italics, but I do think there's value there in conveying the author's original emphasis. What I find quickest in this situation is to go back through the book pretty quickly doing _nothing but italicizing_. I've got Vim setup so that I can highlight the text and hit `,i`, and the text is surrounded by the asterisks, so it makes it pretty quick.

---

As far as Roman numeral references, that's something that I am doing, not Google! Personally, I just find the Roman numeral references to be a "stumbling block", to use Biblical reference! All books of the Bible are being un-abbreviated as well, or at least they should be. 

My reasoning, for what it's worth: I don't want the modern, possibly first time classic reader's train of thought to be broken because they's trying to figure out where `Psa XCVIII. 4` means. We eliminate that risk if we just switch it to `Psalm 98:4`. I want there to be as little distractions to reading the classics as possible!

**Comment by physicswizkid** [comment]
Also, what do you want done with all the stuff after the text? Like the other works by the author and other things like that.

**Comment by lukewil** [comment]
**Delete it.** Once I get to the end of the _actual_ book text, I just always `Command + Shift + Down-Arrow` and delete, (or `dG` in Vim). 

I like the idea of having a list of other books by the author at the end, but this would need to be done manually anyway for these books, because any book but the last wouldn't have them all listed! 😉

**Pull request merged**
