### PR TITLE
*Happy Christian* edited through Chapter 3

### PR DESCRIPTION
**Pull request by hudapaba**
- Edit through Ch. 23
- Fix em-dash spacing (I told you I would)
- Please verify formatting of footnotes

### CODE REVIEW

**Comment by lukewil** [comment]
The footnotes look good except that it needs a blank line before/after. So it should look like

```
Text with footnote[^1]

[^1]: Footnote

Next paragraph.
```

If you commit and push this change to _your_ repo, I believe it will automatically be added to this pull request.

**Comment by hudapaba** [comment]
Luke, Where is the blank line missing?

**Comment by lukewil** [comment]
So sorry, my mistake. I looked at it on Github and the whole not-soft-wrapping-the-lines thing threw me off and I thought it was missing the blank lines. It's not.

Sorry! :confused:

**Comment by hudapaba** [comment]
No problem.

**Pull request merged**
