### PR TITLE
"Have Mercy Upon Me" proofed + formatted.

### PR DESCRIPTION
**Pull request by truthsword**
full text
proofed; formatted

### CODE REVIEW

**Comment by lukewil** [comment]
Thanks so much Bob - you're rolling through these Murray books in a hurry!

Did you notice any missing words in this one?

**Comment by lukewil** [comment]
Also, just glancing through the file: what's the reasoning behind escaping the period in numbered lists, like on line 84 of _Have Mercy Upon Me_?

**Comment by truthsword** [comment]
Again "self-sacrifice" was absent once... just a blank space where it
should have been.

Also... and I think it was in this book... I ran across a few sentences
appended to a paragraph, that I later found missing in a subsequent
paragraph in that chapter.

I added in the Scottish Psalter text that began each major section. I
wasn't quite sure how to distinguish the major sections from each day's
devotional, so I prefaced both as chapters.

Bob

**Comment by truthsword** [comment]
Good question... and I'd appreciate feedback as I've used this before.
Three issues with Markdown...

When you have a numbered list... Markdown always starts with "1"... no
matter the number you use. Look at line 195 as it illustrates the problem
more clearly. If you remove the "\" after the "3", the markdown view shows
a "1" in place of the "3", so we lose verse context.

You'll also see that the text now appears indented. Maybe that's desirable,
or maybe not. But displaying the improper verse number is surely an issue,
unless you have an alternate means to do this.

Another reason for the escape involves numbered lists where multiple
paragraphs occur. Look at line 3 of The Deeper Christian Life.

You'll see that paragraphs 2 and 3 are part of item "1". But when that
occurs, item "2" displays as "1" because the Markdown saw the intervening
paragraphs as a reason to begin numbering again when "2." appeared.
Unfortunately Markdown would display "2." as "1." ... a nonsensical result.

To work around Markdown limitations, I had 2 ways at hand.
1. I could "escape" the numbers, so they would appear as dumb text", or
   instead
2. I blocked paragraphs 2 and 3 as code, which enabled "2." to appear as
   "2."

The only difference I see is that this list is now uniformly indented. Had
I chosen the "escape" approach, instead of adding the code block, the list
would have begun at the left margin

I hope this explanation is somewhat clear. I'm not sure how this all plays
out with the system you are using but the escape was added to overcome
Markdown limitations.

I'd welcome feedback on any of this...

Bob

**Comment by lukewil** [comment]
Gotcha. I see what you mean, it's just been long enough since I've dealt with that I'd forgotten - not that many authors of this era used lists like that. This is great stuff to work through so that we can put it in the documentation, though!

So there are two separate issues here: (1) numbered lists continuing with non-related text in between, and (2) multi-paragraphed numbered lists. So, in that order:
1.  You are absolutely correct - the best thing to do is  **escape the period with a slash**. If needs to be indented in print or online, we'll just do it manually.
2.  In a multiple paragraph item in an numbered list, **all subsequent paragraphs must be preceded by a blank line (like normal) and then indented four spaces**.
   
   This would _normally_ be creating a code block like you mentioned, but in this case it's used to convey the fact that the paragraph belongs with the line item. If you actually wanted to include code, it would have to be indented _eight_ spaces to work here. You can see the breakdown in the [Pandoc documentation here](http://pandoc.org/README.html#the-four-space-rule) - Pandoc is the tool I use to convert to all the other formats.

And see there, I practiced multiple paragraph line items in this comment just to make sure I was right! :wink:

**Comment by truthsword** [comment]
Got it. With _The Deeper Christian Life,_ I took out the code block and
indented the related paragraphs (4 spaces) separated with empty lines
between paragraphs and that worked as you said. I'll implement that going
forward.

**Pull request merged**
