### PR TITLE
added chapter 1 and chapter breaks

### PR DESCRIPTION
**Pull request by truthsword**
OCR text was missing chapters 1 & 2; I added chapter 1, and will add chapter
2 later.

Would like style guidance on:
1. Author's use of chapter CAPS
2. Appropriate use of em-dash (I used "--")

This is my first edit, so maybe you expect more per pull request..

Question... How do I know whether others are making the same edits.
Seems wasteful if more than one are editing the same text.

After I committed/synced, I lost my local copy of changed text. Not sure how I managed that (I have a copy elsewhere), so I'm not sure how to continue this book until my initial changes are brought into master.

### CODE REVIEW

**Comment by lukewil** [comment]
First question: WHO ARE YOU? I can't tell by the name "truthsword". 😉

Second: you achieve some kind of status for being the first pull request! Not trying to be overly dramatic, but this is a momentous occasion!

This is exactly the kind of discussion that makes Github so great for this kind of stuff. On the guidance:
1.  **All caps should never be used.** The OCR engine can't tell the difference between all caps and small caps, but typographically there's a big difference. On the web, in ebooks, and most of all in print, caps is something that we need to avoid.
   
   These are subject headers in the chapter. There's a bit of a judgment call here, but I'd say they're level 3 headers - level 1 is chapter breaks, level 2 would be major theme shifts in a chapter, which these aren't. So I'd call them level 3 headings, which means the line should start with `###`, and be in Title Case. 
2. In the flavor of markdown we're using (Pandoc), `--` is actually an en-dash. **`---` is an em-dash.**

---

No, I think this is a great size per pull-request for now - honestly I don't think we'll know for sure what the right level of changes before pull request will be. I think it will depend on the frequency, the amount of users, etc. Hopefully we'll have a ton!

And actually the question about editing plays into that as well. I'll merge this pull request, and then when everyone syncs they'll get the newly updated version of _The Deeper Christian Life_. So frequent/smaller pull requests and merges create an environment where people aren't duplicating work.

**Comment by truthsword** [comment]
Thanks...

I'm, "Bob Sutton" (just updated profile) - and I'm still trying to grapple
with the GitHub workflow, but that will come.

Thanks for the clarifications... I'll stick with en-dash "--" for now, and
work on the level 3 headers in the text I'm now editing (and I've been
convicted by this book already... yikes!).

Help me with a clarification on commit/sync/pull...
1. After I made my initial pull request, I made some additional edits. When
   I committed/synced these, it appeared that they got tacked onto the
   original pull request... is that correct? So I don't have to make a second
   pull request unless the previous one has been processed?
2. After you merge my pull requests, do I then re-clone the repo before I
   reopen the text file for editing, or will syncing with the GitHub app do
   that for me.

Sorry for the all the questions, but I couldn't find answers on the web
site.

Bob

**Comment by lukewil** [comment]
Thanks Bob - I've never managed a project on Github, either, so we're both learning!

If you didn't find your edited version yet, you can get it back easily now that I've merged your pull request.

I don't know if you're on a Mac or PC, but all I can show you is the Mac version. You should be able to just click on the master, then click `deeproots/master` and then "Sync" in the top right corner. Then you should be up to date with the new and improved version!

master-1
master-2

**Comment by truthsword** [comment]
Thanks! I managed to work things out. I'm on my 3rd text now, and holding back new commits until you have time to process my backlog. 

Stay strong bro'

**Pull request merged**
